#pragma once



namespace engine::render::shaders
{

#define SHADER_VERISON(version)										"#version " version "\n"

#define SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(name, type, location)		"layout(location=" #location ") in " type " " name ";\n"
#define SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(name, type, location)		"layout(location=" #location ") out " type " " name ";\n"
#define SHADER_DEFINE_INPUT_FRAGMENT_ATTRIBUTE(name, type, location)	"layout(location=" #location ") in " type " " name ";\n"
#define SHADER_DEFINE_OUTPUT_FRAGMENT_ATTRIBUTE(name, type, location)	"layout(location=" #location ") out " type " " name ";\n"

#define SHADER_DEFINE_UNIFORM(name, type)							"uniform " type " " name ";\n"
#define SHADER_DEFINE_UNIFORM_WITH_LAYOUT(name, type, unit)			"layout (binding = " unit ")uniform " type " " name ";\n"

#define SHADER_DEFINE_SAMPLER2D(name, unit)								SHADER_DEFINE_UNIFORM_WITH_LAYOUT(name, "sampler2D", unit)



#define	SHADER_IN_VERTEX_ATTRIBUTE_POSITION_NAME					"vPosition"
#define	SHADER_IN_VERTEX_ATTRIBUTE_POSITION_TYPE					"vec3"

#define	SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_NAME						"vNormal"
#define	SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_TYPE						"vec3"

#define	SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_NAME					"vTexCoord"
#define	SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_TYPE					"vec2"

#define SHADER_IN_VERTEX_ATTRIBUTE_COLOR_NAME						"vColor"
#define	SHADER_IN_VERTEX_ATTRIBUTE_COLOR_TYPE						"vec3"


#define SHADER_DEFINE_INPUT_POSITION_VERTEX_ATTRIBUTE				SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_POSITION_NAME,	SHADER_IN_VERTEX_ATTRIBUTE_POSITION_TYPE,	0)
#define SHADER_DEFINE_INPUT_NORMAL_VERTEX_ATTRIBUTE					SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_NAME,	SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_TYPE,		1)
#define SHADER_DEFINE_INPUT_TEXCOORD_VERTEX_ATTRIBUTE				SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_NAME,	SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_TYPE,	2)
#define SHADER_DEFINE_INPUT_COLOR_VERTEX_ATTRIBUTE					SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_COLOR_NAME,		SHADER_IN_VERTEX_ATTRIBUTE_COLOR_TYPE,		3)




#define SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_NAME						"fColor"
#define	SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_TYPE						"vec4"
#define SHADER_OUT_VERTEX_ATTRIBUTE_TEXCOORD_NAME					"fTexCoord"
#define	SHADER_OUT_VERTEX_ATTRIBUTE_TEXCOORD_TYPE					"vec2"
#define SHADER_OUT_VERTEX_ATTRIBUTE_NORMAL_NAME						"fNormalEye"
#define	SHADER_OUT_VERTEX_ATTRIBUTE_NORMAL_TYPE						"vec3"
#define SHADER_OUT_VERTEX_ATTRIBUTE_POSITION_NAME					"fPositionEye"
#define	SHADER_OUT_VERTEX_ATTRIBUTE_POSITION_TYPE					"vec3"



#define SHADER_DEFINE_OUTPUT_COLOR_VERTEX_ATTRIBUTE					SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_NAME,		SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_TYPE,			0)
#define SHADER_DEFINE_OUTPUT_TEXCOORD_VERTEX_ATTRIBUTE				SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(SHADER_OUT_VERTEX_ATTRIBUTE_TEXCOORD_NAME,	SHADER_OUT_VERTEX_ATTRIBUTE_TEXCOORD_TYPE,		1)
#define SHADER_DEFINE_OUTPUT_NORMAL_VERTEX_ATTRIBUTE				SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(SHADER_OUT_VERTEX_ATTRIBUTE_NORMAL_NAME,		SHADER_OUT_VERTEX_ATTRIBUTE_NORMAL_TYPE,		2)
#define SHADER_DEFINE_OUTPUT_POSITION_VERTEX_ATTRIBUTE				SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(SHADER_OUT_VERTEX_ATTRIBUTE_POSITION_NAME,	SHADER_OUT_VERTEX_ATTRIBUTE_POSITION_TYPE,		3)



#define SHADER_IN_FRAGMENT_ATTRIBUTE_COLOR_NAME						"fColor"
#define	SHADER_IN_FRAGMENT_ATTRIBUTE_COLOR_TYPE						"vec4"
#define SHADER_IN_FRAGMENT_ATTRIBUTE_TEXCOORD_NAME					"fTexCoord"
#define	SHADER_IN_FRAGMENT_ATTRIBUTE_TEXCOORD_TYPE					"vec2"
#define SHADER_IN_FRAGMENT_ATTRIBUTE_NORMAL_NAME					"fNormalEye"
#define	SHADER_IN_FRAGMENT_ATTRIBUTE_NORMAL_TYPE					"vec3"
#define SHADER_IN_FRAGMENT_ATTRIBUTE_POSITION_NAME					"fPositionEye"
#define	SHADER_IN_FRAGMENT_ATTRIBUTE_POSITION_TYPE					"vec3"



#define SHADER_DEFINE_INPUT_COLOR_FRAGMENT_ATTRIBUTE				SHADER_DEFINE_INPUT_FRAGMENT_ATTRIBUTE(SHADER_IN_FRAGMENT_ATTRIBUTE_COLOR_NAME,		SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_TYPE,			0)
#define SHADER_DEFINE_INPUT_TEXCOORD_FRAGMENT_ATTRIBUTE				SHADER_DEFINE_INPUT_FRAGMENT_ATTRIBUTE(SHADER_IN_FRAGMENT_ATTRIBUTE_TEXCOORD_NAME,	SHADER_OUT_VERTEX_ATTRIBUTE_TEXCOORD_TYPE,		1)
#define SHADER_DEFINE_INPUT_NORMAL_FRAGMENT_ATTRIBUTE				SHADER_DEFINE_INPUT_FRAGMENT_ATTRIBUTE(SHADER_IN_FRAGMENT_ATTRIBUTE_NORMAL_NAME,		SHADER_OUT_VERTEX_ATTRIBUTE_NORMAL_TYPE,		2)
#define SHADER_DEFINE_INPUT_POSITION_FRAGMENT_ATTRIBUTE				SHADER_DEFINE_INPUT_FRAGMENT_ATTRIBUTE(SHADER_IN_FRAGMENT_ATTRIBUTE_POSITION_NAME,	SHADER_OUT_VERTEX_ATTRIBUTE_POSITION_TYPE,		3)



#define SHADER_OUT_FRAGMENT_ATTRIBUTE_COLOR_NAME					"fragColor"
#define	SHADER_OUT_FRAGMENT_ATTRIBUTE_COLOR_TYPE					"vec4"



#define SHADER_DEFINE_OUTPUT_COLOR_FRAGMENT_ATTRIBUTE				SHADER_DEFINE_OUTPUT_FRAGMENT_ATTRIBUTE(SHADER_OUT_FRAGMENT_ATTRIBUTE_COLOR_NAME,		SHADER_OUT_FRAGMENT_ATTRIBUTE_COLOR_TYPE,			0)	



#define SHADER_UNIFORM_MODEL_TRANSFORM								"uModelTransform"
#define SHADER_UNIFORM_VIEW_TRANSFORM								"uViewTransform"
#define SHADER_UNIFORM_PROJECTION_TRANSFORM							"uProjectionTransform"
#define SHADER_UNIFORM_MODEL_VIEW_TRANSFORM							"uModelViewTransform"
#define SHADER_UNIFORM_MODEL_VIEW_PROJECTION_TRANSFORM				"uModelViewProjectionTransform"
#define SHADER_UNIFORM_NORMAL_MATRIX								"uNormalMatrix"

#define SHADER_UNIFORM_SOURCE_LIGHT_COLOR							"uSourceLightColor"
#define SHADER_UNIFORM_SOURCE_LIGHT_POSITION						"uSourceLightPosition"
#define SHADER_UNIFORM_AMBIENT_FACTOR								"uAmbientFactor"
#define SHADER_UNIFORM_DIFFUSE_FACTOR								"uDiffuseFactor"
#define SHADER_UNIFORM_SPECULAR_FACTOR								"uSpecularFactor"
#define SHADER_UNIFORM_SHINIESS										"uShiniess"


#define SHADER_UNIFORM_COLOR0										"uColor0"

#define SHADER_UNIFORM_COLOR0_TYPE									"vec4"

}