#pragma once



namespace engine::render
{

#define SHADER_VERISON(version)										"#version " version

#define SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(name, type, location)	"layout(location=" #location ") in " type " " name ";
#define SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(name, type, location)	"layout(location=" #location ") out " type " " name ";

#define SHADER_DEFINE_UNIFORM(name, type)							"uniform " type " " name ";

#define SHADER_DEFINE_SAMPLER2D(name)								SHADER_DEFINE_UNIFORM(name, "sampler2D")



#define	SHADER_IN_VERTEX_ATTRIBUTE_POSITION_NAME					"vPosition"
#define	SHADER_IN_VERTEX_ATTRIBUTE_POSITION_TYPE					"vec3"

#define	SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_NAME						"vNormal"
#define	SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_TYPE						"vec3"

#define	SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_NAME					"vTexCoord"
#define	SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_TYPE					"vec2"

#define SHADER_IN_VERTEX_ATTRIBUTE_COLOR_NAME						"vColor"
#define	SHADER_IN_VERTEX_ATTRIBUTE_COLOR_TYPE						"vec3"


#define SHADER_DEFINE_INPUT_POSITION_VERTEX_ATTRIBUTE				SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_POSITION_NAME,	SHADER_IN_VERTEX_ATTRIBUTE_POSITION_TYPE,	0)
#define SHADER_DEFINE_INPUT_NORMAL_VERTEX_ATTRIBUTE					SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_NAME,	SHADER_IN_VERTEX_ATTRIBUTE_NORMAL_TYPE,		1)
#define SHADER_DEFINE_INPUT_TEXCOORD_VERTEX_ATTRIBUTE				SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_NAME,	SHADER_IN_VERTEX_ATTRIBUTE_TEXCOORD_TYPE,	2)
#define SHADER_DEFINE_INPUT_COLOR_VERTEX_ATTRIBUTE					SHADER_DEFINE_INPUT_VERTEX_ATTRIBUTE(SHADER_IN_VERTEX_ATTRIBUTE_COLOR_NAME,		SHADER_IN_VERTEX_ATTRIBUTE_COLOR_TYPE,		3)




#define SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_NAME						"vColor"
#define	SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_TYPE						"vec4"


#define SHADER_DEFINE_OUTPUT_COLOR_VERTEX_ATTRIBUTE					SHADER_DEFINE_OUTPUT_VERTEX_ATTRIBUTE(SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_NAME,	SHADER_OUT_VERTEX_ATTRIBUTE_COLOR_TYPE,		0)



#define SHADER_UNIFORM_MODEL_TRANSFORM								"uModelTransform"
#define SHADER_UNIFORM_VIEW_TRANSFORM								"uViewTransform"
#define SHADER_UNIFORM_PROJECTION_TRANSFORM							"uProjectionTransform"

#define SHADER_UNIFORM_COLOR0										"uColor0"

#define SHADER_UNIFORM_COLOR0_TYPE									"vec4"

}